import { User, Project, Task, ActivityItem, NotificationItem, DashboardMetrics, Client } from '../types';

const now = new Date();
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000).toISOString();
const fiveDaysAgo = new Date(now.getTime() - 5 * 24 * 60 * 60 * 1000).toISOString();
const twoDaysAhead = new Date(now.getTime() + 2 * 24 * 60 * 60 * 1000).toISOString();
const fiveDaysAhead = new Date(now.getTime() + 5 * 24 * 60 * 60 * 1000).toISOString();
const tenDaysAhead = new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000).toISOString();

export const mockUsers: User[] = [
  {
    id: 'usr_admin_01',
    name: 'Sarah Admin',
    email: 'admin@velozity.com',
    role: 'ADMIN',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
  },
  {
    id: 'usr_pm_01',
    name: 'Ravi Sharma',
    email: 'ravi.pm@velozity.com',
    role: 'PROJECT_MANAGER',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
  },
  {
    id: 'usr_pm_02',
    name: 'Elena Vance',
    email: 'elena.pm@velozity.com',
    role: 'PROJECT_MANAGER',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
  },
  {
    id: 'usr_dev_01',
    name: 'Alex Chen',
    email: 'alex.dev@velozity.com',
    role: 'DEVELOPER',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
  },
  {
    id: 'usr_dev_02',
    name: 'Marcus Miller',
    email: 'marcus.dev@velozity.com',
    role: 'DEVELOPER',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150',
  },
  {
    id: 'usr_dev_03',
    name: 'Priya Patel',
    email: 'priya.dev@velozity.com',
    role: 'DEVELOPER',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
  },
  {
    id: 'usr_dev_04',
    name: 'David Kim',
    email: 'david.dev@velozity.com',
    role: 'DEVELOPER',
    avatarUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150',
  },
];

export const mockClients: Client[] = [
  {
    id: 'clt_01',
    name: 'Acme Financial Group',
    email: 'contact@acmefinancial.com',
    company: 'Acme Financial Inc.',
    phone: '+1 (555) 234-5678',
    createdAt: now.toISOString(),
  },
  {
    id: 'clt_02',
    name: 'Nova Healthtech Systems',
    email: 'partners@novahealth.org',
    company: 'Nova Health Corp',
    phone: '+1 (555) 876-5432',
    createdAt: now.toISOString(),
  },
  {
    id: 'clt_03',
    name: 'OmniFleet Global Logistics',
    email: 'operations@omnifleet.io',
    company: 'OmniFleet Worldwide',
    phone: '+1 (555) 345-6789',
    createdAt: now.toISOString(),
  },
];

export let mockProjects: Project[] = [
  {
    id: 'prj_01',
    name: 'Next-Gen Fintech Portal',
    description: 'Zero-trust multi-currency banking platform with automated compliance checks.',
    status: 'ACTIVE',
    clientId: 'clt_01',
    client: mockClients[0],
    managerId: 'usr_pm_01', // Ravi
    manager: mockUsers[1],
    createdAt: threeDaysAgo,
    updatedAt: now.toISOString(),
    _count: { tasks: 6 },
  },
  {
    id: 'prj_02',
    name: 'Healthcare Telemedicine App',
    description: 'HIPAA-compliant video consults, prescription routing, and patient portal.',
    status: 'ACTIVE',
    clientId: 'clt_02',
    client: mockClients[1],
    managerId: 'usr_pm_02', // Elena
    manager: mockUsers[2],
    createdAt: fiveDaysAgo,
    updatedAt: now.toISOString(),
    _count: { tasks: 5 },
  },
  {
    id: 'prj_03',
    name: 'Global Fleet Tracking IoT',
    description: 'Real-time telemetry, geo-fencing, and predictive maintenance dispatch.',
    status: 'ACTIVE',
    clientId: 'clt_03',
    client: mockClients[2],
    managerId: 'usr_pm_01', // Ravi
    manager: mockUsers[1],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
    _count: { tasks: 5 },
  },
];

export let mockTasks: Task[] = [
  {
    id: 'tsk_01',
    taskNumber: 1,
    title: 'Architect JWT Authentication & Session Service',
    description: 'Implement secure access/refresh token rotation with HttpOnly cookies.',
    status: 'DONE',
    priority: 'CRITICAL',
    dueDate: threeDaysAgo,
    isOverdue: false,
    projectId: 'prj_01',
    project: { id: 'prj_01', name: 'Next-Gen Fintech Portal', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_01',
    developer: mockUsers[3],
    createdAt: threeDaysAgo,
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_02',
    taskNumber: 2,
    title: 'Ledger Reconciliation Microservice Pipeline',
    description: 'Process batch transactions and identify ledger discrepancies.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: fiveDaysAgo,
    isOverdue: true,
    projectId: 'prj_01',
    project: { id: 'prj_01', name: 'Next-Gen Fintech Portal', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_01',
    developer: mockUsers[3],
    createdAt: fiveDaysAgo,
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_03',
    taskNumber: 3,
    title: 'ACH Wire Transfer API Integration',
    description: 'Integrate Plaid and Stripe Treasury for real-time fund transfers.',
    status: 'IN_REVIEW',
    priority: 'CRITICAL',
    dueDate: twoDaysAhead,
    isOverdue: false,
    projectId: 'prj_01',
    project: { id: 'prj_01', name: 'Next-Gen Fintech Portal', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_02',
    developer: mockUsers[4],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_04',
    taskNumber: 4,
    title: 'Fraud Detection Rule Engine Setup',
    description: 'Flag anomalous transactions based on velocity thresholds.',
    status: 'TODO',
    priority: 'HIGH',
    dueDate: fiveDaysAhead,
    isOverdue: false,
    projectId: 'prj_01',
    project: { id: 'prj_01', name: 'Next-Gen Fintech Portal', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_02',
    developer: mockUsers[4],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_05',
    taskNumber: 5,
    title: 'Customer KYC Document Verification Flow',
    description: 'ID card upload and biometric liveness verification pipeline.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    dueDate: tenDaysAhead,
    isOverdue: false,
    projectId: 'prj_01',
    project: { id: 'prj_01', name: 'Next-Gen Fintech Portal', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_01',
    developer: mockUsers[3],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_06',
    taskNumber: 6,
    title: 'Audit Trail Export to S3 Cold Storage',
    description: 'Daily automated snapshot and GPG-encrypted archiving.',
    status: 'TODO',
    priority: 'LOW',
    dueDate: tenDaysAhead,
    isOverdue: false,
    projectId: 'prj_01',
    project: { id: 'prj_01', name: 'Next-Gen Fintech Portal', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_02',
    developer: mockUsers[4],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_07',
    taskNumber: 7,
    title: 'WebRTC Encrypted Video Calling Gateway',
    description: 'End-to-end encrypted peer-to-peer consult room with TURN relay.',
    status: 'IN_REVIEW',
    priority: 'CRITICAL',
    dueDate: threeDaysAgo,
    isOverdue: true,
    projectId: 'prj_02',
    project: { id: 'prj_02', name: 'Healthcare Telemedicine App', managerId: 'usr_pm_02' },
    developerId: 'usr_dev_03',
    developer: mockUsers[5],
    createdAt: threeDaysAgo,
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_08',
    taskNumber: 8,
    title: 'FHIR Medical Records Sync Engine',
    description: 'Bi-directional synchronization with hospital HL7 FHIR APIs.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: twoDaysAhead,
    isOverdue: false,
    projectId: 'prj_02',
    project: { id: 'prj_02', name: 'Healthcare Telemedicine App', managerId: 'usr_pm_02' },
    developerId: 'usr_dev_03',
    developer: mockUsers[5],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_09',
    taskNumber: 9,
    title: 'Prescription Digital Signature Provider',
    description: 'Cryptographic signing for e-prescriptions sent to pharmacies.',
    status: 'DONE',
    priority: 'MEDIUM',
    dueDate: fiveDaysAgo,
    isOverdue: false,
    projectId: 'prj_02',
    project: { id: 'prj_02', name: 'Healthcare Telemedicine App', managerId: 'usr_pm_02' },
    developerId: 'usr_dev_04',
    developer: mockUsers[6],
    createdAt: fiveDaysAgo,
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_10',
    taskNumber: 10,
    title: 'Patient Push Notification Dispatcher',
    description: 'Appointment reminders via APNS/FCM and SMS fallback.',
    status: 'TODO',
    priority: 'MEDIUM',
    dueDate: fiveDaysAhead,
    isOverdue: false,
    projectId: 'prj_02',
    project: { id: 'prj_02', name: 'Healthcare Telemedicine App', managerId: 'usr_pm_02' },
    developerId: 'usr_dev_04',
    developer: mockUsers[6],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_11',
    taskNumber: 11,
    title: 'Doctor Availability Calendar Grid',
    description: 'Slot generation with timezone compensation and double-booking guard.',
    status: 'IN_PROGRESS',
    priority: 'HIGH',
    dueDate: twoDaysAhead,
    isOverdue: false,
    projectId: 'prj_02',
    project: { id: 'prj_02', name: 'Healthcare Telemedicine App', managerId: 'usr_pm_02' },
    developerId: 'usr_dev_03',
    developer: mockUsers[5],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_12',
    taskNumber: 12,
    title: 'MQTT Vehicle Telemetry Ingestion Broker',
    description: 'High-throughput broker processing 50k packets/sec from OBD-II units.',
    status: 'IN_PROGRESS',
    priority: 'CRITICAL',
    dueDate: twoDaysAhead,
    isOverdue: false,
    projectId: 'prj_03',
    project: { id: 'prj_03', name: 'Global Fleet Tracking IoT', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_01',
    developer: mockUsers[3],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_13',
    taskNumber: 13,
    title: 'Geofencing Polygon Violation Trigger',
    description: 'Spatial queries using PostGIS to detect route deviation.',
    status: 'TODO',
    priority: 'HIGH',
    dueDate: fiveDaysAhead,
    isOverdue: false,
    projectId: 'prj_03',
    project: { id: 'prj_03', name: 'Global Fleet Tracking IoT', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_04',
    developer: mockUsers[6],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_14',
    taskNumber: 14,
    title: 'Driver Hours-of-Service Compliance Reporter',
    description: 'DOT electronic logging device compliance calculation engine.',
    status: 'IN_REVIEW',
    priority: 'MEDIUM',
    dueDate: twoDaysAhead,
    isOverdue: false,
    projectId: 'prj_03',
    project: { id: 'prj_03', name: 'Global Fleet Tracking IoT', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_01',
    developer: mockUsers[3],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_15',
    taskNumber: 15,
    title: 'Fuel Consumption Anomaly Detection',
    description: 'Statistical anomaly detection on fuel tank level vs distance covered.',
    status: 'TODO',
    priority: 'LOW',
    dueDate: tenDaysAhead,
    isOverdue: false,
    projectId: 'prj_03',
    project: { id: 'prj_03', name: 'Global Fleet Tracking IoT', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_04',
    developer: mockUsers[6],
    createdAt: now.toISOString(),
    updatedAt: now.toISOString(),
  },
  {
    id: 'tsk_16',
    taskNumber: 16,
    title: 'Cellular SIM Provisioning and Diagnostics',
    description: 'Integration with telecom eSIM activation and roaming status API.',
    status: 'DONE',
    priority: 'MEDIUM',
    dueDate: threeDaysAgo,
    isOverdue: false,
    projectId: 'prj_03',
    project: { id: 'prj_03', name: 'Global Fleet Tracking IoT', managerId: 'usr_pm_01' },
    developerId: 'usr_dev_02',
    developer: mockUsers[4],
    createdAt: threeDaysAgo,
    updatedAt: now.toISOString(),
  },
];

export let mockActivities: ActivityItem[] = [
  {
    id: 'act_01',
    taskId: 'tsk_03',
    taskNumber: 3,
    taskTitle: 'ACH Wire Transfer API Integration',
    projectId: 'prj_01',
    projectName: 'Next-Gen Fintech Portal',
    userId: 'usr_dev_02',
    userName: 'Marcus Miller',
    action: 'STATUS_CHANGED',
    description: 'Marcus Miller moved Task #3 from In Progress → In Review',
    createdAt: new Date(now.getTime() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_02',
    taskId: 'tsk_14',
    taskNumber: 14,
    taskTitle: 'Driver Hours-of-Service Compliance Reporter',
    projectId: 'prj_03',
    projectName: 'Global Fleet Tracking IoT',
    userId: 'usr_dev_01',
    userName: 'Alex Chen',
    action: 'STATUS_CHANGED',
    description: 'Alex Chen moved Task #14 from In Progress → In Review',
    createdAt: new Date(now.getTime() - 25 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_03',
    taskId: 'tsk_02',
    taskNumber: 2,
    taskTitle: 'Ledger Reconciliation Microservice Pipeline',
    projectId: 'prj_01',
    projectName: 'Next-Gen Fintech Portal',
    userId: 'usr_admin_01',
    userName: 'Sarah Admin',
    action: 'OVERDUE_FLAGGED',
    description: 'System flagged Task #2 ("Ledger Reconciliation Microservice Pipeline") as Overdue',
    createdAt: new Date(now.getTime() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_04',
    taskId: 'tsk_07',
    taskNumber: 7,
    taskTitle: 'WebRTC Encrypted Video Calling Gateway',
    projectId: 'prj_02',
    projectName: 'Healthcare Telemedicine App',
    userId: 'usr_admin_01',
    userName: 'Sarah Admin',
    action: 'OVERDUE_FLAGGED',
    description: 'System flagged Task #7 ("WebRTC Encrypted Video Calling Gateway") as Overdue',
    createdAt: new Date(now.getTime() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_05',
    taskId: 'tsk_01',
    taskNumber: 1,
    taskTitle: 'Architect JWT Authentication & Session Service',
    projectId: 'prj_01',
    projectName: 'Next-Gen Fintech Portal',
    userId: 'usr_pm_01',
    userName: 'Ravi Sharma',
    action: 'STATUS_CHANGED',
    description: 'Ravi Sharma moved Task #1 from In Review → Done',
    createdAt: new Date(now.getTime() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act_06',
    taskId: 'tsk_08',
    taskNumber: 8,
    taskTitle: 'FHIR Medical Records Sync Engine',
    projectId: 'prj_02',
    projectName: 'Healthcare Telemedicine App',
    userId: 'usr_dev_03',
    userName: 'Priya Patel',
    action: 'STATUS_CHANGED',
    description: 'Priya Patel moved Task #8 from To Do → In Progress',
    createdAt: new Date(now.getTime() - 4 * 60 * 60 * 1000).toISOString(),
  },
];

export let mockNotifications: NotificationItem[] = [
  {
    id: 'notif_01',
    userId: 'usr_pm_01',
    title: 'Task Ready for Review',
    message: 'Marcus Miller moved Task #3 ("ACH Wire Transfer API Integration") to In Review',
    type: 'TASK_STATUS_CHANGED',
    isRead: false,
    link: '/projects/prj_01',
    createdAt: new Date(now.getTime() - 8 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif_02',
    userId: 'usr_pm_02',
    title: 'Task Overdue in Project',
    message: 'Task #7 ("WebRTC Encrypted Video Calling Gateway") in "Healthcare Telemedicine App" is overdue.',
    type: 'TASK_OVERDUE',
    isRead: false,
    link: '/projects/prj_02',
    createdAt: new Date(now.getTime() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'notif_03',
    userId: 'usr_dev_01',
    title: 'Task Overdue',
    message: 'Task #2 ("Ledger Reconciliation Microservice Pipeline") is now overdue!',
    type: 'TASK_OVERDUE',
    isRead: false,
    link: '/projects/prj_01',
    createdAt: new Date(now.getTime() - 45 * 60 * 1000).toISOString(),
  },
];
